# Generated by Django 4.2.7 on 2023-11-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('tamaño', models.TextField(null=True, verbose_name='Tamaño')),
                ('descarga', models.TextField(null=True, verbose_name='descarga')),
            ],
        ),
    ]
